apiVersion: v1
kind: Service
metadata:
  name: clustered-app
spec:
  type: LoadBalancer
  selector:
    cluster: clustered-app
  ports:
    - name: hazelcast
      port: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
